// <auto-generated />
using System;
using ChessMonitor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChessMonitor.Api.Migrations
{
    [DbContext(typeof(ChessMonitorDbContext))]
    [Migration("20260401044642_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChessMonitor.Api.Data.Entities.AnalysisResultEntity", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<DateTimeOffset>("AnalyzedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at_utc");

                    b.Property<decimal?>("AverageCentipawnLoss")
                        .HasColumnType("numeric")
                        .HasColumnName("average_centipawn_loss");

                    b.Property<int>("Blunders")
                        .HasColumnType("integer")
                        .HasColumnName("blunders");

                    b.Property<int>("Inaccuracies")
                        .HasColumnType("integer")
                        .HasColumnName("inaccuracies");

                    b.Property<int>("Mistakes")
                        .HasColumnType("integer")
                        .HasColumnName("mistakes");

                    b.HasKey("GameId");

                    b.ToTable("analysis_results", (string)null);
                });

            modelBuilder.Entity("ChessMonitor.Api.Data.Entities.ChessGameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlackPlayer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("black_player");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalGameId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_game_id");

                    b.Property<string>("OpeningCode")
                        .HasColumnType("text")
                        .HasColumnName("opening_code");

                    b.Property<string>("OpeningName")
                        .HasColumnType("text")
                        .HasColumnName("opening_name");

                    b.Property<string>("Pgn")
                        .HasColumnType("text")
                        .HasColumnName("pgn");

                    b.Property<DateTimeOffset>("PlayedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at_utc");

                    b.Property<string>("PlayerUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_username");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("TimeControl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_control");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WhitePlayer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("white_player");

                    b.HasKey("Id");

                    b.HasIndex("SourceSystem", "ExternalGameId")
                        .IsUnique();

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("ChessMonitor.Api.Data.Entities.AnalysisResultEntity", b =>
                {
                    b.HasOne("ChessMonitor.Api.Data.Entities.ChessGameEntity", "Game")
                        .WithOne("AnalysisResult")
                        .HasForeignKey("ChessMonitor.Api.Data.Entities.AnalysisResultEntity", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChessMonitor.Api.Data.Entities.ChessGameEntity", b =>
                {
                    b.Navigation("AnalysisResult");
                });
#pragma warning restore 612, 618
        }
    }
}
